<?php


/**
 * This class adds structure of 'cp_cities' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun May  3 20:31:47 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CpCitiesMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CpCitiesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CpCitiesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CpCitiesPeer::TABLE_NAME);
		$tMap->setPhpName('CpCities');
		$tMap->setClassname('CpCities');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addForeignKey('STATE_ID', 'StateId', 'INTEGER', 'cp_states', 'ID', true, 11);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 100);

		$tMap->addColumn('LATITUDE', 'Latitude', 'DECIMAL', false, 18);

		$tMap->addColumn('LONGITUDE', 'Longitude', 'DECIMAL', false, 18);

	} // doBuild()

} // CpCitiesMapBuilder
