<?php


/**
 * This class adds structure of 'equip_function' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/28/09 19:43:55
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EquipFunctionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EquipFunctionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EquipFunctionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EquipFunctionPeer::TABLE_NAME);
		$tMap->setPhpName('EquipFunction');
		$tMap->setClassname('EquipFunction');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('FUNCTION_ID', 'FunctionId', 'INTEGER', true, 10);

		$tMap->addColumn('FUNCTION_NAME', 'FunctionName', 'VARCHAR', true, 45);

	} // doBuild()

} // EquipFunctionMapBuilder
