<?php


/**
 * This class adds structure of 'user_rides' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/27/09 21:49:15
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserRidesMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserRidesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UserRidesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UserRidesPeer::TABLE_NAME);
		$tMap->setPhpName('UserRides');
		$tMap->setClassname('UserRides');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('USER_RIDE_ID', 'UserRideId', 'INTEGER', true, 10);

		$tMap->addForeignKey('RIDE_ID', 'RideId', 'INTEGER', 'rides', 'RIDE_KEY', true, 10);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'users', 'USER_ID', true, 10);

		$tMap->addColumn('DESCRIPTION', 'Description', 'VARCHAR', true, 45);

		$tMap->addColumn('MILEAGE', 'Mileage', 'DECIMAL', true, 10);

		$tMap->addColumn('ALTITUDE_GAIN', 'AltitudeGain', 'DECIMAL', true, 10);

	} // doBuild()

} // UserRidesMapBuilder
