<?php


/**
 * This class adds structure of 'user_stats' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun May  3 20:31:47 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserStatsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserStatsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UserStatsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UserStatsPeer::TABLE_NAME);
		$tMap->setPhpName('UserStats');
		$tMap->setClassname('UserStats');

		$tMap->setUseIdGenerator(true);

		$tMap->addColumn('USER_ID', 'UserId', 'INTEGER', true, 10);

		$tMap->addColumn('RIDE_DATE', 'RideDate', 'TIMESTAMP', true, null);

		$tMap->addColumn('RIDE_TIME', 'RideTime', 'DECIMAL', true, 10);

		$tMap->addColumn('AVG_SPEED', 'AvgSpeed', 'DECIMAL', true, 10);

		$tMap->addColumn('CALORIES_BURNED', 'CaloriesBurned', 'DECIMAL', true, 10);

		$tMap->addPrimaryKey('STAT_NO', 'StatNo', 'INTEGER', true, 10);

		$tMap->addForeignKey('RIDE_KEY', 'RideKey', 'INTEGER', 'user_rides', 'USER_RIDE_ID', true, 10);

		$tMap->addForeignKey('BIKE_ID', 'BikeId', 'INTEGER', 'user_bikes', 'USER_BIKE_ID', true, 10);

	} // doBuild()

} // UserStatsMapBuilder
