<?php


/**
 * This class adds structure of 'user_equipement' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun May 31 11:53:55 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserEquipementMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserEquipementMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UserEquipementPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UserEquipementPeer::TABLE_NAME);
		$tMap->setPhpName('UserEquipement');
		$tMap->setClassname('UserEquipement');

		$tMap->setUseIdGenerator(true);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'users', 'USER_ID', true, 10);

		$tMap->addPrimaryKey('EQUIPMENT_ID', 'EquipmentId', 'INTEGER', true, 10);

		$tMap->addColumn('DESCRIPTION', 'Description', 'VARCHAR', true, 45);

		$tMap->addForeignKey('BIKE_ID', 'BikeId', 'INTEGER', 'user_bikes', 'USER_BIKE_ID', false, 10);

		$tMap->addColumn('EQUIP_FUNCTION', 'EquipFunction', 'INTEGER', true, 10);

		$tMap->addColumn('PURCHASE_PRICE', 'PurchasePrice', 'DECIMAL', true, 10);

		$tMap->addColumn('PURCHASE_DATE', 'PurchaseDate', 'DATE', false, null);

		$tMap->addColumn('MAKE', 'Make', 'VARCHAR', false, 50);

		$tMap->addColumn('MODEL', 'Model', 'VARCHAR', false, 50);

	} // doBuild()

} // UserEquipementMapBuilder
