<?php

/**
 * Base class that represents a row from the 'user_equipement' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/27/09 21:49:15
 *
 * @package    lib.model.om
 */
abstract class BaseUserEquipement extends BaseObject  implements Persistent {


  const PEER = 'UserEquipementPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserEquipementPeer
	 */
	protected static $peer;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the equipment_id field.
	 * @var        int
	 */
	protected $equipment_id;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the bike_id field.
	 * @var        int
	 */
	protected $bike_id;

	/**
	 * The value for the equip_function field.
	 * @var        int
	 */
	protected $equip_function;

	/**
	 * The value for the purchase_price field.
	 * Note: this column has a database default value of: '0.00'
	 * @var        string
	 */
	protected $purchase_price;

	/**
	 * The value for the purchase_date field.
	 * @var        string
	 */
	protected $purchase_date;

	/**
	 * The value for the make field.
	 * @var        string
	 */
	protected $make;

	/**
	 * The value for the model field.
	 * @var        string
	 */
	protected $model;

	/**
	 * @var        Users
	 */
	protected $aUsers;

	/**
	 * @var        UserBikes
	 */
	protected $aUserBikes;

	/**
	 * @var        array UserStatEquip[] Collection to store aggregation of UserStatEquip objects.
	 */
	protected $collUserStatEquips;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserStatEquips.
	 */
	private $lastUserStatEquipCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUserEquipement object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->purchase_price = '0.00';
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [equipment_id] column value.
	 * 
	 * @return     int
	 */
	public function getEquipmentId()
	{
		return $this->equipment_id;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [bike_id] column value.
	 * 
	 * @return     int
	 */
	public function getBikeId()
	{
		return $this->bike_id;
	}

	/**
	 * Get the [equip_function] column value.
	 * 
	 * @return     int
	 */
	public function getEquipFunction()
	{
		return $this->equip_function;
	}

	/**
	 * Get the [purchase_price] column value.
	 * 
	 * @return     string
	 */
	public function getPurchasePrice()
	{
		return $this->purchase_price;
	}

	/**
	 * Get the [optionally formatted] temporal [purchase_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getPurchaseDate($format = 'Y-m-d')
	{
		if ($this->purchase_date === null) {
			return null;
		}


		if ($this->purchase_date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->purchase_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->purchase_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [make] column value.
	 * 
	 * @return     string
	 */
	public function getMake()
	{
		return $this->make;
	}

	/**
	 * Get the [model] column value.
	 * 
	 * @return     string
	 */
	public function getModel()
	{
		return $this->model;
	}

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = UserEquipementPeer::USER_ID;
		}

		if ($this->aUsers !== null && $this->aUsers->getUserId() !== $v) {
			$this->aUsers = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [equipment_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setEquipmentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->equipment_id !== $v) {
			$this->equipment_id = $v;
			$this->modifiedColumns[] = UserEquipementPeer::EQUIPMENT_ID;
		}

		return $this;
	} // setEquipmentId()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = UserEquipementPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [bike_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setBikeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bike_id !== $v) {
			$this->bike_id = $v;
			$this->modifiedColumns[] = UserEquipementPeer::BIKE_ID;
		}

		if ($this->aUserBikes !== null && $this->aUserBikes->getUserBikeId() !== $v) {
			$this->aUserBikes = null;
		}

		return $this;
	} // setBikeId()

	/**
	 * Set the value of [equip_function] column.
	 * 
	 * @param      int $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setEquipFunction($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->equip_function !== $v) {
			$this->equip_function = $v;
			$this->modifiedColumns[] = UserEquipementPeer::EQUIP_FUNCTION;
		}

		return $this;
	} // setEquipFunction()

	/**
	 * Set the value of [purchase_price] column.
	 * 
	 * @param      string $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setPurchasePrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->purchase_price !== $v || $v === '0.00') {
			$this->purchase_price = $v;
			$this->modifiedColumns[] = UserEquipementPeer::PURCHASE_PRICE;
		}

		return $this;
	} // setPurchasePrice()

	/**
	 * Sets the value of [purchase_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setPurchaseDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->purchase_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->purchase_date !== null && $tmpDt = new DateTime($this->purchase_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->purchase_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = UserEquipementPeer::PURCHASE_DATE;
			}
		} // if either are not null

		return $this;
	} // setPurchaseDate()

	/**
	 * Set the value of [make] column.
	 * 
	 * @param      string $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setMake($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->make !== $v) {
			$this->make = $v;
			$this->modifiedColumns[] = UserEquipementPeer::MAKE;
		}

		return $this;
	} // setMake()

	/**
	 * Set the value of [model] column.
	 * 
	 * @param      string $v new value
	 * @return     UserEquipement The current object (for fluent API support)
	 */
	public function setModel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->model !== $v) {
			$this->model = $v;
			$this->modifiedColumns[] = UserEquipementPeer::MODEL;
		}

		return $this;
	} // setModel()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(UserEquipementPeer::PURCHASE_PRICE))) {
				return false;
			}

			if ($this->purchase_price !== '0.00') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->user_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->equipment_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->description = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->bike_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->equip_function = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->purchase_price = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->purchase_date = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->make = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->model = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = UserEquipementPeer::NUM_COLUMNS - UserEquipementPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating UserEquipement object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsers !== null && $this->user_id !== $this->aUsers->getUserId()) {
			$this->aUsers = null;
		}
		if ($this->aUserBikes !== null && $this->bike_id !== $this->aUserBikes->getUserBikeId()) {
			$this->aUserBikes = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserEquipementPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserEquipementPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsers = null;
			$this->aUserBikes = null;
			$this->collUserStatEquips = null;
			$this->lastUserStatEquipCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserEquipement:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserEquipementPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UserEquipementPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUserEquipement:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserEquipement:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserEquipementPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUserEquipement:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UserEquipementPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsers !== null) {
				if ($this->aUsers->isModified() || $this->aUsers->isNew()) {
					$affectedRows += $this->aUsers->save($con);
				}
				$this->setUsers($this->aUsers);
			}

			if ($this->aUserBikes !== null) {
				if ($this->aUserBikes->isModified() || $this->aUserBikes->isNew()) {
					$affectedRows += $this->aUserBikes->save($con);
				}
				$this->setUserBikes($this->aUserBikes);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserEquipementPeer::EQUIPMENT_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserEquipementPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setEquipmentId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserEquipementPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collUserStatEquips !== null) {
				foreach ($this->collUserStatEquips as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsers !== null) {
				if (!$this->aUsers->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsers->getValidationFailures());
				}
			}

			if ($this->aUserBikes !== null) {
				if (!$this->aUserBikes->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUserBikes->getValidationFailures());
				}
			}


			if (($retval = UserEquipementPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collUserStatEquips !== null) {
					foreach ($this->collUserStatEquips as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserEquipementPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUserId();
				break;
			case 1:
				return $this->getEquipmentId();
				break;
			case 2:
				return $this->getDescription();
				break;
			case 3:
				return $this->getBikeId();
				break;
			case 4:
				return $this->getEquipFunction();
				break;
			case 5:
				return $this->getPurchasePrice();
				break;
			case 6:
				return $this->getPurchaseDate();
				break;
			case 7:
				return $this->getMake();
				break;
			case 8:
				return $this->getModel();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserEquipementPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUserId(),
			$keys[1] => $this->getEquipmentId(),
			$keys[2] => $this->getDescription(),
			$keys[3] => $this->getBikeId(),
			$keys[4] => $this->getEquipFunction(),
			$keys[5] => $this->getPurchasePrice(),
			$keys[6] => $this->getPurchaseDate(),
			$keys[7] => $this->getMake(),
			$keys[8] => $this->getModel(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserEquipementPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUserId($value);
				break;
			case 1:
				$this->setEquipmentId($value);
				break;
			case 2:
				$this->setDescription($value);
				break;
			case 3:
				$this->setBikeId($value);
				break;
			case 4:
				$this->setEquipFunction($value);
				break;
			case 5:
				$this->setPurchasePrice($value);
				break;
			case 6:
				$this->setPurchaseDate($value);
				break;
			case 7:
				$this->setMake($value);
				break;
			case 8:
				$this->setModel($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserEquipementPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUserId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setEquipmentId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDescription($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setBikeId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEquipFunction($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPurchasePrice($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPurchaseDate($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setMake($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setModel($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserEquipementPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserEquipementPeer::USER_ID)) $criteria->add(UserEquipementPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(UserEquipementPeer::EQUIPMENT_ID)) $criteria->add(UserEquipementPeer::EQUIPMENT_ID, $this->equipment_id);
		if ($this->isColumnModified(UserEquipementPeer::DESCRIPTION)) $criteria->add(UserEquipementPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(UserEquipementPeer::BIKE_ID)) $criteria->add(UserEquipementPeer::BIKE_ID, $this->bike_id);
		if ($this->isColumnModified(UserEquipementPeer::EQUIP_FUNCTION)) $criteria->add(UserEquipementPeer::EQUIP_FUNCTION, $this->equip_function);
		if ($this->isColumnModified(UserEquipementPeer::PURCHASE_PRICE)) $criteria->add(UserEquipementPeer::PURCHASE_PRICE, $this->purchase_price);
		if ($this->isColumnModified(UserEquipementPeer::PURCHASE_DATE)) $criteria->add(UserEquipementPeer::PURCHASE_DATE, $this->purchase_date);
		if ($this->isColumnModified(UserEquipementPeer::MAKE)) $criteria->add(UserEquipementPeer::MAKE, $this->make);
		if ($this->isColumnModified(UserEquipementPeer::MODEL)) $criteria->add(UserEquipementPeer::MODEL, $this->model);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserEquipementPeer::DATABASE_NAME);

		$criteria->add(UserEquipementPeer::EQUIPMENT_ID, $this->equipment_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getEquipmentId();
	}

	/**
	 * Generic method to set the primary key (equipment_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setEquipmentId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of UserEquipement (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserId($this->user_id);

		$copyObj->setDescription($this->description);

		$copyObj->setBikeId($this->bike_id);

		$copyObj->setEquipFunction($this->equip_function);

		$copyObj->setPurchasePrice($this->purchase_price);

		$copyObj->setPurchaseDate($this->purchase_date);

		$copyObj->setMake($this->make);

		$copyObj->setModel($this->model);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getUserStatEquips() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserStatEquip($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setEquipmentId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     UserEquipement Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserEquipementPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserEquipementPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Users object.
	 *
	 * @param      Users $v
	 * @return     UserEquipement The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsers(Users $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getUserId());
		}

		$this->aUsers = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Users object, it will not be re-added.
		if ($v !== null) {
			$v->addUserEquipement($this);
		}

		return $this;
	}


	/**
	 * Get the associated Users object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Users The associated Users object.
	 * @throws     PropelException
	 */
	public function getUsers(PropelPDO $con = null)
	{
		if ($this->aUsers === null && ($this->user_id !== null)) {
			$c = new Criteria(UsersPeer::DATABASE_NAME);
			$c->add(UsersPeer::USER_ID, $this->user_id);
			$this->aUsers = UsersPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsers->addUserEquipements($this);
			 */
		}
		return $this->aUsers;
	}

	/**
	 * Declares an association between this object and a UserBikes object.
	 *
	 * @param      UserBikes $v
	 * @return     UserEquipement The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserBikes(UserBikes $v = null)
	{
		if ($v === null) {
			$this->setBikeId(NULL);
		} else {
			$this->setBikeId($v->getUserBikeId());
		}

		$this->aUserBikes = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the UserBikes object, it will not be re-added.
		if ($v !== null) {
			$v->addUserEquipement($this);
		}

		return $this;
	}


	/**
	 * Get the associated UserBikes object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     UserBikes The associated UserBikes object.
	 * @throws     PropelException
	 */
	public function getUserBikes(PropelPDO $con = null)
	{
		if ($this->aUserBikes === null && ($this->bike_id !== null)) {
			$c = new Criteria(UserBikesPeer::DATABASE_NAME);
			$c->add(UserBikesPeer::USER_BIKE_ID, $this->bike_id);
			$this->aUserBikes = UserBikesPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUserBikes->addUserEquipements($this);
			 */
		}
		return $this->aUserBikes;
	}

	/**
	 * Clears out the collUserStatEquips collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserStatEquips()
	 */
	public function clearUserStatEquips()
	{
		$this->collUserStatEquips = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserStatEquips collection (array).
	 *
	 * By default this just sets the collUserStatEquips collection to an empty array (like clearcollUserStatEquips());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserStatEquips()
	{
		$this->collUserStatEquips = array();
	}

	/**
	 * Gets an array of UserStatEquip objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this UserEquipement has previously been saved, it will retrieve
	 * related UserStatEquips from storage. If this UserEquipement is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserStatEquip[]
	 * @throws     PropelException
	 */
	public function getUserStatEquips($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserEquipementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserStatEquips === null) {
			if ($this->isNew()) {
			   $this->collUserStatEquips = array();
			} else {

				$criteria->add(UserStatEquipPeer::USER_EQUIP_ID, $this->equipment_id);

				UserStatEquipPeer::addSelectColumns($criteria);
				$this->collUserStatEquips = UserStatEquipPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserStatEquipPeer::USER_EQUIP_ID, $this->equipment_id);

				UserStatEquipPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserStatEquipCriteria) || !$this->lastUserStatEquipCriteria->equals($criteria)) {
					$this->collUserStatEquips = UserStatEquipPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserStatEquipCriteria = $criteria;
		return $this->collUserStatEquips;
	}

	/**
	 * Returns the number of related UserStatEquip objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserStatEquip objects.
	 * @throws     PropelException
	 */
	public function countUserStatEquips(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserEquipementPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserStatEquips === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserStatEquipPeer::USER_EQUIP_ID, $this->equipment_id);

				$count = UserStatEquipPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserStatEquipPeer::USER_EQUIP_ID, $this->equipment_id);

				if (!isset($this->lastUserStatEquipCriteria) || !$this->lastUserStatEquipCriteria->equals($criteria)) {
					$count = UserStatEquipPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserStatEquips);
				}
			} else {
				$count = count($this->collUserStatEquips);
			}
		}
		$this->lastUserStatEquipCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserStatEquip object to this object
	 * through the UserStatEquip foreign key attribute.
	 *
	 * @param      UserStatEquip $l UserStatEquip
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserStatEquip(UserStatEquip $l)
	{
		if ($this->collUserStatEquips === null) {
			$this->initUserStatEquips();
		}
		if (!in_array($l, $this->collUserStatEquips, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserStatEquips, $l);
			$l->setUserEquipement($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this UserEquipement is new, it will return
	 * an empty collection; or if this UserEquipement has previously
	 * been saved, it will retrieve related UserStatEquips from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in UserEquipement.
	 */
	public function getUserStatEquipsJoinUserStats($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserEquipementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserStatEquips === null) {
			if ($this->isNew()) {
				$this->collUserStatEquips = array();
			} else {

				$criteria->add(UserStatEquipPeer::USER_EQUIP_ID, $this->equipment_id);

				$this->collUserStatEquips = UserStatEquipPeer::doSelectJoinUserStats($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserStatEquipPeer::USER_EQUIP_ID, $this->equipment_id);

			if (!isset($this->lastUserStatEquipCriteria) || !$this->lastUserStatEquipCriteria->equals($criteria)) {
				$this->collUserStatEquips = UserStatEquipPeer::doSelectJoinUserStats($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserStatEquipCriteria = $criteria;

		return $this->collUserStatEquips;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collUserStatEquips) {
				foreach ((array) $this->collUserStatEquips as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collUserStatEquips = null;
			$this->aUsers = null;
			$this->aUserBikes = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUserEquipement:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUserEquipement::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUserEquipement
