<?php

/**
 * Base class that represents a row from the 'user_bikes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/27/09 21:49:15
 *
 * @package    lib.model.om
 */
abstract class BaseUserBikes extends BaseObject  implements Persistent {


  const PEER = 'UserBikesPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserBikesPeer
	 */
	protected static $peer;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the user_bike_id field.
	 * @var        int
	 */
	protected $user_bike_id;

	/**
	 * The value for the bike_year field.
	 * @var        int
	 */
	protected $bike_year;

	/**
	 * The value for the bike_make field.
	 * @var        string
	 */
	protected $bike_make;

	/**
	 * The value for the bike_model field.
	 * @var        string
	 */
	protected $bike_model;

	/**
	 * The value for the equip_function field.
	 * @var        int
	 */
	protected $equip_function;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * @var        Users
	 */
	protected $aUsers;

	/**
	 * @var        array UserEquipement[] Collection to store aggregation of UserEquipement objects.
	 */
	protected $collUserEquipements;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserEquipements.
	 */
	private $lastUserEquipementCriteria = null;

	/**
	 * @var        array UserStats[] Collection to store aggregation of UserStats objects.
	 */
	protected $collUserStatss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserStatss.
	 */
	private $lastUserStatsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUserBikes object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [user_bike_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserBikeId()
	{
		return $this->user_bike_id;
	}

	/**
	 * Get the [bike_year] column value.
	 * 
	 * @return     int
	 */
	public function getBikeYear()
	{
		return $this->bike_year;
	}

	/**
	 * Get the [bike_make] column value.
	 * 
	 * @return     string
	 */
	public function getBikeMake()
	{
		return $this->bike_make;
	}

	/**
	 * Get the [bike_model] column value.
	 * 
	 * @return     string
	 */
	public function getBikeModel()
	{
		return $this->bike_model;
	}

	/**
	 * Get the [equip_function] column value.
	 * 
	 * @return     int
	 */
	public function getEquipFunction()
	{
		return $this->equip_function;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = UserBikesPeer::USER_ID;
		}

		if ($this->aUsers !== null && $this->aUsers->getUserId() !== $v) {
			$this->aUsers = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [user_bike_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setUserBikeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_bike_id !== $v) {
			$this->user_bike_id = $v;
			$this->modifiedColumns[] = UserBikesPeer::USER_BIKE_ID;
		}

		return $this;
	} // setUserBikeId()

	/**
	 * Set the value of [bike_year] column.
	 * 
	 * @param      int $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setBikeYear($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bike_year !== $v) {
			$this->bike_year = $v;
			$this->modifiedColumns[] = UserBikesPeer::BIKE_YEAR;
		}

		return $this;
	} // setBikeYear()

	/**
	 * Set the value of [bike_make] column.
	 * 
	 * @param      string $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setBikeMake($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->bike_make !== $v) {
			$this->bike_make = $v;
			$this->modifiedColumns[] = UserBikesPeer::BIKE_MAKE;
		}

		return $this;
	} // setBikeMake()

	/**
	 * Set the value of [bike_model] column.
	 * 
	 * @param      string $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setBikeModel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->bike_model !== $v) {
			$this->bike_model = $v;
			$this->modifiedColumns[] = UserBikesPeer::BIKE_MODEL;
		}

		return $this;
	} // setBikeModel()

	/**
	 * Set the value of [equip_function] column.
	 * 
	 * @param      int $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setEquipFunction($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->equip_function !== $v) {
			$this->equip_function = $v;
			$this->modifiedColumns[] = UserBikesPeer::EQUIP_FUNCTION;
		}

		return $this;
	} // setEquipFunction()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     UserBikes The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = UserBikesPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->user_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_bike_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->bike_year = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->bike_make = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->bike_model = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->equip_function = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->description = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = UserBikesPeer::NUM_COLUMNS - UserBikesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating UserBikes object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsers !== null && $this->user_id !== $this->aUsers->getUserId()) {
			$this->aUsers = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserBikesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserBikesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsers = null;
			$this->collUserEquipements = null;
			$this->lastUserEquipementCriteria = null;

			$this->collUserStatss = null;
			$this->lastUserStatsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserBikes:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserBikesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UserBikesPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUserBikes:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserBikes:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserBikesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUserBikes:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UserBikesPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsers !== null) {
				if ($this->aUsers->isModified() || $this->aUsers->isNew()) {
					$affectedRows += $this->aUsers->save($con);
				}
				$this->setUsers($this->aUsers);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserBikesPeer::USER_BIKE_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserBikesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setUserBikeId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserBikesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collUserEquipements !== null) {
				foreach ($this->collUserEquipements as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserStatss !== null) {
				foreach ($this->collUserStatss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsers !== null) {
				if (!$this->aUsers->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsers->getValidationFailures());
				}
			}


			if (($retval = UserBikesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collUserEquipements !== null) {
					foreach ($this->collUserEquipements as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserStatss !== null) {
					foreach ($this->collUserStatss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserBikesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUserId();
				break;
			case 1:
				return $this->getUserBikeId();
				break;
			case 2:
				return $this->getBikeYear();
				break;
			case 3:
				return $this->getBikeMake();
				break;
			case 4:
				return $this->getBikeModel();
				break;
			case 5:
				return $this->getEquipFunction();
				break;
			case 6:
				return $this->getDescription();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserBikesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUserId(),
			$keys[1] => $this->getUserBikeId(),
			$keys[2] => $this->getBikeYear(),
			$keys[3] => $this->getBikeMake(),
			$keys[4] => $this->getBikeModel(),
			$keys[5] => $this->getEquipFunction(),
			$keys[6] => $this->getDescription(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserBikesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUserId($value);
				break;
			case 1:
				$this->setUserBikeId($value);
				break;
			case 2:
				$this->setBikeYear($value);
				break;
			case 3:
				$this->setBikeMake($value);
				break;
			case 4:
				$this->setBikeModel($value);
				break;
			case 5:
				$this->setEquipFunction($value);
				break;
			case 6:
				$this->setDescription($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserBikesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUserId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserBikeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setBikeYear($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setBikeMake($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setBikeModel($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEquipFunction($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDescription($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserBikesPeer::USER_ID)) $criteria->add(UserBikesPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(UserBikesPeer::USER_BIKE_ID)) $criteria->add(UserBikesPeer::USER_BIKE_ID, $this->user_bike_id);
		if ($this->isColumnModified(UserBikesPeer::BIKE_YEAR)) $criteria->add(UserBikesPeer::BIKE_YEAR, $this->bike_year);
		if ($this->isColumnModified(UserBikesPeer::BIKE_MAKE)) $criteria->add(UserBikesPeer::BIKE_MAKE, $this->bike_make);
		if ($this->isColumnModified(UserBikesPeer::BIKE_MODEL)) $criteria->add(UserBikesPeer::BIKE_MODEL, $this->bike_model);
		if ($this->isColumnModified(UserBikesPeer::EQUIP_FUNCTION)) $criteria->add(UserBikesPeer::EQUIP_FUNCTION, $this->equip_function);
		if ($this->isColumnModified(UserBikesPeer::DESCRIPTION)) $criteria->add(UserBikesPeer::DESCRIPTION, $this->description);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);

		$criteria->add(UserBikesPeer::USER_BIKE_ID, $this->user_bike_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getUserBikeId();
	}

	/**
	 * Generic method to set the primary key (user_bike_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setUserBikeId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of UserBikes (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserId($this->user_id);

		$copyObj->setBikeYear($this->bike_year);

		$copyObj->setBikeMake($this->bike_make);

		$copyObj->setBikeModel($this->bike_model);

		$copyObj->setEquipFunction($this->equip_function);

		$copyObj->setDescription($this->description);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getUserEquipements() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserEquipement($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserStatss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserStats($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setUserBikeId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     UserBikes Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserBikesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserBikesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Users object.
	 *
	 * @param      Users $v
	 * @return     UserBikes The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsers(Users $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getUserId());
		}

		$this->aUsers = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Users object, it will not be re-added.
		if ($v !== null) {
			$v->addUserBikes($this);
		}

		return $this;
	}


	/**
	 * Get the associated Users object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Users The associated Users object.
	 * @throws     PropelException
	 */
	public function getUsers(PropelPDO $con = null)
	{
		if ($this->aUsers === null && ($this->user_id !== null)) {
			$c = new Criteria(UsersPeer::DATABASE_NAME);
			$c->add(UsersPeer::USER_ID, $this->user_id);
			$this->aUsers = UsersPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsers->addUserBikess($this);
			 */
		}
		return $this->aUsers;
	}

	/**
	 * Clears out the collUserEquipements collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserEquipements()
	 */
	public function clearUserEquipements()
	{
		$this->collUserEquipements = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserEquipements collection (array).
	 *
	 * By default this just sets the collUserEquipements collection to an empty array (like clearcollUserEquipements());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserEquipements()
	{
		$this->collUserEquipements = array();
	}

	/**
	 * Gets an array of UserEquipement objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this UserBikes has previously been saved, it will retrieve
	 * related UserEquipements from storage. If this UserBikes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserEquipement[]
	 * @throws     PropelException
	 */
	public function getUserEquipements($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserEquipements === null) {
			if ($this->isNew()) {
			   $this->collUserEquipements = array();
			} else {

				$criteria->add(UserEquipementPeer::BIKE_ID, $this->user_bike_id);

				UserEquipementPeer::addSelectColumns($criteria);
				$this->collUserEquipements = UserEquipementPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserEquipementPeer::BIKE_ID, $this->user_bike_id);

				UserEquipementPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserEquipementCriteria) || !$this->lastUserEquipementCriteria->equals($criteria)) {
					$this->collUserEquipements = UserEquipementPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserEquipementCriteria = $criteria;
		return $this->collUserEquipements;
	}

	/**
	 * Returns the number of related UserEquipement objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserEquipement objects.
	 * @throws     PropelException
	 */
	public function countUserEquipements(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserEquipements === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserEquipementPeer::BIKE_ID, $this->user_bike_id);

				$count = UserEquipementPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserEquipementPeer::BIKE_ID, $this->user_bike_id);

				if (!isset($this->lastUserEquipementCriteria) || !$this->lastUserEquipementCriteria->equals($criteria)) {
					$count = UserEquipementPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserEquipements);
				}
			} else {
				$count = count($this->collUserEquipements);
			}
		}
		$this->lastUserEquipementCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserEquipement object to this object
	 * through the UserEquipement foreign key attribute.
	 *
	 * @param      UserEquipement $l UserEquipement
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserEquipement(UserEquipement $l)
	{
		if ($this->collUserEquipements === null) {
			$this->initUserEquipements();
		}
		if (!in_array($l, $this->collUserEquipements, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserEquipements, $l);
			$l->setUserBikes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this UserBikes is new, it will return
	 * an empty collection; or if this UserBikes has previously
	 * been saved, it will retrieve related UserEquipements from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in UserBikes.
	 */
	public function getUserEquipementsJoinUsers($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserEquipements === null) {
			if ($this->isNew()) {
				$this->collUserEquipements = array();
			} else {

				$criteria->add(UserEquipementPeer::BIKE_ID, $this->user_bike_id);

				$this->collUserEquipements = UserEquipementPeer::doSelectJoinUsers($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserEquipementPeer::BIKE_ID, $this->user_bike_id);

			if (!isset($this->lastUserEquipementCriteria) || !$this->lastUserEquipementCriteria->equals($criteria)) {
				$this->collUserEquipements = UserEquipementPeer::doSelectJoinUsers($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserEquipementCriteria = $criteria;

		return $this->collUserEquipements;
	}

	/**
	 * Clears out the collUserStatss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserStatss()
	 */
	public function clearUserStatss()
	{
		$this->collUserStatss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserStatss collection (array).
	 *
	 * By default this just sets the collUserStatss collection to an empty array (like clearcollUserStatss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserStatss()
	{
		$this->collUserStatss = array();
	}

	/**
	 * Gets an array of UserStats objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this UserBikes has previously been saved, it will retrieve
	 * related UserStatss from storage. If this UserBikes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserStats[]
	 * @throws     PropelException
	 */
	public function getUserStatss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserStatss === null) {
			if ($this->isNew()) {
			   $this->collUserStatss = array();
			} else {

				$criteria->add(UserStatsPeer::BIKE_ID, $this->user_bike_id);

				UserStatsPeer::addSelectColumns($criteria);
				$this->collUserStatss = UserStatsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserStatsPeer::BIKE_ID, $this->user_bike_id);

				UserStatsPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserStatsCriteria) || !$this->lastUserStatsCriteria->equals($criteria)) {
					$this->collUserStatss = UserStatsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserStatsCriteria = $criteria;
		return $this->collUserStatss;
	}

	/**
	 * Returns the number of related UserStats objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserStats objects.
	 * @throws     PropelException
	 */
	public function countUserStatss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserStatss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserStatsPeer::BIKE_ID, $this->user_bike_id);

				$count = UserStatsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserStatsPeer::BIKE_ID, $this->user_bike_id);

				if (!isset($this->lastUserStatsCriteria) || !$this->lastUserStatsCriteria->equals($criteria)) {
					$count = UserStatsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserStatss);
				}
			} else {
				$count = count($this->collUserStatss);
			}
		}
		$this->lastUserStatsCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserStats object to this object
	 * through the UserStats foreign key attribute.
	 *
	 * @param      UserStats $l UserStats
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserStats(UserStats $l)
	{
		if ($this->collUserStatss === null) {
			$this->initUserStatss();
		}
		if (!in_array($l, $this->collUserStatss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserStatss, $l);
			$l->setUserBikes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this UserBikes is new, it will return
	 * an empty collection; or if this UserBikes has previously
	 * been saved, it will retrieve related UserStatss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in UserBikes.
	 */
	public function getUserStatssJoinUserRides($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserBikesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserStatss === null) {
			if ($this->isNew()) {
				$this->collUserStatss = array();
			} else {

				$criteria->add(UserStatsPeer::BIKE_ID, $this->user_bike_id);

				$this->collUserStatss = UserStatsPeer::doSelectJoinUserRides($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserStatsPeer::BIKE_ID, $this->user_bike_id);

			if (!isset($this->lastUserStatsCriteria) || !$this->lastUserStatsCriteria->equals($criteria)) {
				$this->collUserStatss = UserStatsPeer::doSelectJoinUserRides($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserStatsCriteria = $criteria;

		return $this->collUserStatss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collUserEquipements) {
				foreach ((array) $this->collUserEquipements as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserStatss) {
				foreach ((array) $this->collUserStatss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collUserEquipements = null;
		$this->collUserStatss = null;
			$this->aUsers = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUserBikes:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUserBikes::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUserBikes
