<?php

/**
 * Base class that represents a row from the 'users' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/28/09 19:43:56
 *
 * @package    lib.model.om
 */
abstract class BaseUsers extends BaseObject  implements Persistent {


  const PEER = 'UsersPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UsersPeer
	 */
	protected static $peer;

	/**
	 * The value for the username field.
	 * @var        string
	 */
	protected $username;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the fname field.
	 * @var        string
	 */
	protected $fname;

	/**
	 * The value for the lname field.
	 * @var        string
	 */
	protected $lname;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the salt field.
	 * @var        string
	 */
	protected $salt;

	/**
	 * The value for the active field.
	 * Note: this column has a database default value of: 'N'
	 * @var        string
	 */
	protected $active;

	/**
	 * The value for the join_date field.
	 * @var        string
	 */
	protected $join_date;

	/**
	 * @var        array UserBikes[] Collection to store aggregation of UserBikes objects.
	 */
	protected $collUserBikess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserBikess.
	 */
	private $lastUserBikesCriteria = null;

	/**
	 * @var        array UserEquipement[] Collection to store aggregation of UserEquipement objects.
	 */
	protected $collUserEquipements;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserEquipements.
	 */
	private $lastUserEquipementCriteria = null;

	/**
	 * @var        UserInformation one-to-one related UserInformation object
	 */
	protected $singleUserInformation;

	/**
	 * @var        UserProfile one-to-one related UserProfile object
	 */
	protected $singleUserProfile;

	/**
	 * @var        array UserRides[] Collection to store aggregation of UserRides objects.
	 */
	protected $collUserRidess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserRidess.
	 */
	private $lastUserRidesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUsers object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->active = 'N';
	}

	/**
	 * Get the [username] column value.
	 * 
	 * @return     string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [fname] column value.
	 * 
	 * @return     string
	 */
	public function getFname()
	{
		return $this->fname;
	}

	/**
	 * Get the [lname] column value.
	 * 
	 * @return     string
	 */
	public function getLname()
	{
		return $this->lname;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [salt] column value.
	 * 
	 * @return     string
	 */
	public function getSalt()
	{
		return $this->salt;
	}

	/**
	 * Get the [active] column value.
	 * 
	 * @return     string
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * Get the [optionally formatted] temporal [join_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getJoinDate($format = 'Y-m-d H:i:s')
	{
		if ($this->join_date === null) {
			return null;
		}


		if ($this->join_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->join_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->join_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [username] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUsername($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->username !== $v) {
			$this->username = $v;
			$this->modifiedColumns[] = UsersPeer::USERNAME;
		}

		return $this;
	} // setUsername()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = UsersPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [fname] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setFname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fname !== $v) {
			$this->fname = $v;
			$this->modifiedColumns[] = UsersPeer::FNAME;
		}

		return $this;
	} // setFname()

	/**
	 * Set the value of [lname] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setLname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lname !== $v) {
			$this->lname = $v;
			$this->modifiedColumns[] = UsersPeer::LNAME;
		}

		return $this;
	} // setLname()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = UsersPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = UsersPeer::USER_ID;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [salt] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setSalt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->salt !== $v) {
			$this->salt = $v;
			$this->modifiedColumns[] = UsersPeer::SALT;
		}

		return $this;
	} // setSalt()

	/**
	 * Set the value of [active] column.
	 * 
	 * @param      string $v new value
	 * @return     Users The current object (for fluent API support)
	 */
	public function setActive($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->active !== $v || $v === 'N') {
			$this->active = $v;
			$this->modifiedColumns[] = UsersPeer::ACTIVE;
		}

		return $this;
	} // setActive()

	/**
	 * Sets the value of [join_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Users The current object (for fluent API support)
	 */
	public function setJoinDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->join_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->join_date !== null && $tmpDt = new DateTime($this->join_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->join_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UsersPeer::JOIN_DATE;
			}
		} // if either are not null

		return $this;
	} // setJoinDate()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(UsersPeer::ACTIVE))) {
				return false;
			}

			if ($this->active !== 'N') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->username = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->password = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->fname = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->lname = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->user_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->salt = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->active = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->join_date = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = UsersPeer::NUM_COLUMNS - UsersPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Users object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UsersPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collUserBikess = null;
			$this->lastUserBikesCriteria = null;

			$this->collUserEquipements = null;
			$this->lastUserEquipementCriteria = null;

			$this->singleUserInformation = null;

			$this->singleUserProfile = null;

			$this->collUserRidess = null;
			$this->lastUserRidesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUsers:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UsersPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUsers:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUsers:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUsers:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UsersPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UsersPeer::USER_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UsersPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setUserId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UsersPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collUserBikess !== null) {
				foreach ($this->collUserBikess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserEquipements !== null) {
				foreach ($this->collUserEquipements as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->singleUserInformation !== null) {
				if (!$this->singleUserInformation->isDeleted()) {
						$affectedRows += $this->singleUserInformation->save($con);
				}
			}

			if ($this->singleUserProfile !== null) {
				if (!$this->singleUserProfile->isDeleted()) {
						$affectedRows += $this->singleUserProfile->save($con);
				}
			}

			if ($this->collUserRidess !== null) {
				foreach ($this->collUserRidess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = UsersPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collUserBikess !== null) {
					foreach ($this->collUserBikess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserEquipements !== null) {
					foreach ($this->collUserEquipements as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->singleUserInformation !== null) {
					if (!$this->singleUserInformation->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleUserInformation->getValidationFailures());
					}
				}

				if ($this->singleUserProfile !== null) {
					if (!$this->singleUserProfile->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleUserProfile->getValidationFailures());
					}
				}

				if ($this->collUserRidess !== null) {
					foreach ($this->collUserRidess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUsername();
				break;
			case 1:
				return $this->getPassword();
				break;
			case 2:
				return $this->getFname();
				break;
			case 3:
				return $this->getLname();
				break;
			case 4:
				return $this->getEmail();
				break;
			case 5:
				return $this->getUserId();
				break;
			case 6:
				return $this->getSalt();
				break;
			case 7:
				return $this->getActive();
				break;
			case 8:
				return $this->getJoinDate();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UsersPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUsername(),
			$keys[1] => $this->getPassword(),
			$keys[2] => $this->getFname(),
			$keys[3] => $this->getLname(),
			$keys[4] => $this->getEmail(),
			$keys[5] => $this->getUserId(),
			$keys[6] => $this->getSalt(),
			$keys[7] => $this->getActive(),
			$keys[8] => $this->getJoinDate(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUsername($value);
				break;
			case 1:
				$this->setPassword($value);
				break;
			case 2:
				$this->setFname($value);
				break;
			case 3:
				$this->setLname($value);
				break;
			case 4:
				$this->setEmail($value);
				break;
			case 5:
				$this->setUserId($value);
				break;
			case 6:
				$this->setSalt($value);
				break;
			case 7:
				$this->setActive($value);
				break;
			case 8:
				$this->setJoinDate($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UsersPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUsername($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPassword($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFname($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setLname($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEmail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUserId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setSalt($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setActive($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setJoinDate($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UsersPeer::DATABASE_NAME);

		if ($this->isColumnModified(UsersPeer::USERNAME)) $criteria->add(UsersPeer::USERNAME, $this->username);
		if ($this->isColumnModified(UsersPeer::PASSWORD)) $criteria->add(UsersPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(UsersPeer::FNAME)) $criteria->add(UsersPeer::FNAME, $this->fname);
		if ($this->isColumnModified(UsersPeer::LNAME)) $criteria->add(UsersPeer::LNAME, $this->lname);
		if ($this->isColumnModified(UsersPeer::EMAIL)) $criteria->add(UsersPeer::EMAIL, $this->email);
		if ($this->isColumnModified(UsersPeer::USER_ID)) $criteria->add(UsersPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(UsersPeer::SALT)) $criteria->add(UsersPeer::SALT, $this->salt);
		if ($this->isColumnModified(UsersPeer::ACTIVE)) $criteria->add(UsersPeer::ACTIVE, $this->active);
		if ($this->isColumnModified(UsersPeer::JOIN_DATE)) $criteria->add(UsersPeer::JOIN_DATE, $this->join_date);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UsersPeer::DATABASE_NAME);

		$criteria->add(UsersPeer::USER_ID, $this->user_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getUserId();
	}

	/**
	 * Generic method to set the primary key (user_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setUserId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Users (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsername($this->username);

		$copyObj->setPassword($this->password);

		$copyObj->setFname($this->fname);

		$copyObj->setLname($this->lname);

		$copyObj->setEmail($this->email);

		$copyObj->setSalt($this->salt);

		$copyObj->setActive($this->active);

		$copyObj->setJoinDate($this->join_date);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getUserBikess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserBikes($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserEquipements() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserEquipement($relObj->copy($deepCopy));
				}
			}

			$relObj = $this->getUserInformation();
			if ($relObj) {
				$copyObj->setUserInformation($relObj->copy($deepCopy));
			}

			$relObj = $this->getUserProfile();
			if ($relObj) {
				$copyObj->setUserProfile($relObj->copy($deepCopy));
			}

			foreach ($this->getUserRidess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserRides($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setUserId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Users Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UsersPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UsersPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collUserBikess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserBikess()
	 */
	public function clearUserBikess()
	{
		$this->collUserBikess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserBikess collection (array).
	 *
	 * By default this just sets the collUserBikess collection to an empty array (like clearcollUserBikess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserBikess()
	{
		$this->collUserBikess = array();
	}

	/**
	 * Gets an array of UserBikes objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Users has previously been saved, it will retrieve
	 * related UserBikess from storage. If this Users is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserBikes[]
	 * @throws     PropelException
	 */
	public function getUserBikess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserBikess === null) {
			if ($this->isNew()) {
			   $this->collUserBikess = array();
			} else {

				$criteria->add(UserBikesPeer::USER_ID, $this->user_id);

				UserBikesPeer::addSelectColumns($criteria);
				$this->collUserBikess = UserBikesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserBikesPeer::USER_ID, $this->user_id);

				UserBikesPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserBikesCriteria) || !$this->lastUserBikesCriteria->equals($criteria)) {
					$this->collUserBikess = UserBikesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserBikesCriteria = $criteria;
		return $this->collUserBikess;
	}

	/**
	 * Returns the number of related UserBikes objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserBikes objects.
	 * @throws     PropelException
	 */
	public function countUserBikess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserBikess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserBikesPeer::USER_ID, $this->user_id);

				$count = UserBikesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserBikesPeer::USER_ID, $this->user_id);

				if (!isset($this->lastUserBikesCriteria) || !$this->lastUserBikesCriteria->equals($criteria)) {
					$count = UserBikesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserBikess);
				}
			} else {
				$count = count($this->collUserBikess);
			}
		}
		$this->lastUserBikesCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserBikes object to this object
	 * through the UserBikes foreign key attribute.
	 *
	 * @param      UserBikes $l UserBikes
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserBikes(UserBikes $l)
	{
		if ($this->collUserBikess === null) {
			$this->initUserBikess();
		}
		if (!in_array($l, $this->collUserBikess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserBikess, $l);
			$l->setUsers($this);
		}
	}

	/**
	 * Clears out the collUserEquipements collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserEquipements()
	 */
	public function clearUserEquipements()
	{
		$this->collUserEquipements = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserEquipements collection (array).
	 *
	 * By default this just sets the collUserEquipements collection to an empty array (like clearcollUserEquipements());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserEquipements()
	{
		$this->collUserEquipements = array();
	}

	/**
	 * Gets an array of UserEquipement objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Users has previously been saved, it will retrieve
	 * related UserEquipements from storage. If this Users is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserEquipement[]
	 * @throws     PropelException
	 */
	public function getUserEquipements($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserEquipements === null) {
			if ($this->isNew()) {
			   $this->collUserEquipements = array();
			} else {

				$criteria->add(UserEquipementPeer::USER_ID, $this->user_id);

				UserEquipementPeer::addSelectColumns($criteria);
				$this->collUserEquipements = UserEquipementPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserEquipementPeer::USER_ID, $this->user_id);

				UserEquipementPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserEquipementCriteria) || !$this->lastUserEquipementCriteria->equals($criteria)) {
					$this->collUserEquipements = UserEquipementPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserEquipementCriteria = $criteria;
		return $this->collUserEquipements;
	}

	/**
	 * Returns the number of related UserEquipement objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserEquipement objects.
	 * @throws     PropelException
	 */
	public function countUserEquipements(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserEquipements === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserEquipementPeer::USER_ID, $this->user_id);

				$count = UserEquipementPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserEquipementPeer::USER_ID, $this->user_id);

				if (!isset($this->lastUserEquipementCriteria) || !$this->lastUserEquipementCriteria->equals($criteria)) {
					$count = UserEquipementPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserEquipements);
				}
			} else {
				$count = count($this->collUserEquipements);
			}
		}
		$this->lastUserEquipementCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserEquipement object to this object
	 * through the UserEquipement foreign key attribute.
	 *
	 * @param      UserEquipement $l UserEquipement
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserEquipement(UserEquipement $l)
	{
		if ($this->collUserEquipements === null) {
			$this->initUserEquipements();
		}
		if (!in_array($l, $this->collUserEquipements, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserEquipements, $l);
			$l->setUsers($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Users is new, it will return
	 * an empty collection; or if this Users has previously
	 * been saved, it will retrieve related UserEquipements from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Users.
	 */
	public function getUserEquipementsJoinUserBikes($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserEquipements === null) {
			if ($this->isNew()) {
				$this->collUserEquipements = array();
			} else {

				$criteria->add(UserEquipementPeer::USER_ID, $this->user_id);

				$this->collUserEquipements = UserEquipementPeer::doSelectJoinUserBikes($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserEquipementPeer::USER_ID, $this->user_id);

			if (!isset($this->lastUserEquipementCriteria) || !$this->lastUserEquipementCriteria->equals($criteria)) {
				$this->collUserEquipements = UserEquipementPeer::doSelectJoinUserBikes($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserEquipementCriteria = $criteria;

		return $this->collUserEquipements;
	}

	/**
	 * Gets a single UserInformation object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     UserInformation
	 * @throws     PropelException
	 */
	public function getUserInformation(PropelPDO $con = null)
	{

		if ($this->singleUserInformation === null && !$this->isNew()) {
			$this->singleUserInformation = UserInformationPeer::retrieveByPK($this->user_id, $con);
		}

		return $this->singleUserInformation;
	}

	/**
	 * Sets a single UserInformation object as related to this object by a one-to-one relationship.
	 *
	 * @param      UserInformation $l UserInformation
	 * @return     Users The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserInformation(UserInformation $v)
	{
		$this->singleUserInformation = $v;

		// Make sure that that the passed-in UserInformation isn't already associated with this object
		if ($v->getUsers() === null) {
			$v->setUsers($this);
		}

		return $this;
	}

	/**
	 * Gets a single UserProfile object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     UserProfile
	 * @throws     PropelException
	 */
	public function getUserProfile(PropelPDO $con = null)
	{

		if ($this->singleUserProfile === null && !$this->isNew()) {
			$this->singleUserProfile = UserProfilePeer::retrieveByPK($this->user_id, $con);
		}

		return $this->singleUserProfile;
	}

	/**
	 * Sets a single UserProfile object as related to this object by a one-to-one relationship.
	 *
	 * @param      UserProfile $l UserProfile
	 * @return     Users The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUserProfile(UserProfile $v)
	{
		$this->singleUserProfile = $v;

		// Make sure that that the passed-in UserProfile isn't already associated with this object
		if ($v->getUsers() === null) {
			$v->setUsers($this);
		}

		return $this;
	}

	/**
	 * Clears out the collUserRidess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserRidess()
	 */
	public function clearUserRidess()
	{
		$this->collUserRidess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserRidess collection (array).
	 *
	 * By default this just sets the collUserRidess collection to an empty array (like clearcollUserRidess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserRidess()
	{
		$this->collUserRidess = array();
	}

	/**
	 * Gets an array of UserRides objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Users has previously been saved, it will retrieve
	 * related UserRidess from storage. If this Users is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserRides[]
	 * @throws     PropelException
	 */
	public function getUserRidess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserRidess === null) {
			if ($this->isNew()) {
			   $this->collUserRidess = array();
			} else {

				$criteria->add(UserRidesPeer::USER_ID, $this->user_id);

				UserRidesPeer::addSelectColumns($criteria);
				$this->collUserRidess = UserRidesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserRidesPeer::USER_ID, $this->user_id);

				UserRidesPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserRidesCriteria) || !$this->lastUserRidesCriteria->equals($criteria)) {
					$this->collUserRidess = UserRidesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserRidesCriteria = $criteria;
		return $this->collUserRidess;
	}

	/**
	 * Returns the number of related UserRides objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserRides objects.
	 * @throws     PropelException
	 */
	public function countUserRidess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserRidess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserRidesPeer::USER_ID, $this->user_id);

				$count = UserRidesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserRidesPeer::USER_ID, $this->user_id);

				if (!isset($this->lastUserRidesCriteria) || !$this->lastUserRidesCriteria->equals($criteria)) {
					$count = UserRidesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserRidess);
				}
			} else {
				$count = count($this->collUserRidess);
			}
		}
		$this->lastUserRidesCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserRides object to this object
	 * through the UserRides foreign key attribute.
	 *
	 * @param      UserRides $l UserRides
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserRides(UserRides $l)
	{
		if ($this->collUserRidess === null) {
			$this->initUserRidess();
		}
		if (!in_array($l, $this->collUserRidess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserRidess, $l);
			$l->setUsers($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Users is new, it will return
	 * an empty collection; or if this Users has previously
	 * been saved, it will retrieve related UserRidess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Users.
	 */
	public function getUserRidessJoinRides($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsersPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserRidess === null) {
			if ($this->isNew()) {
				$this->collUserRidess = array();
			} else {

				$criteria->add(UserRidesPeer::USER_ID, $this->user_id);

				$this->collUserRidess = UserRidesPeer::doSelectJoinRides($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserRidesPeer::USER_ID, $this->user_id);

			if (!isset($this->lastUserRidesCriteria) || !$this->lastUserRidesCriteria->equals($criteria)) {
				$this->collUserRidess = UserRidesPeer::doSelectJoinRides($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserRidesCriteria = $criteria;

		return $this->collUserRidess;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collUserBikess) {
				foreach ((array) $this->collUserBikess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserEquipements) {
				foreach ((array) $this->collUserEquipements as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->singleUserInformation) {
				$this->singleUserInformation->clearAllReferences($deep);
			}
			if ($this->singleUserProfile) {
				$this->singleUserProfile->clearAllReferences($deep);
			}
			if ($this->collUserRidess) {
				foreach ((array) $this->collUserRidess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collUserBikess = null;
		$this->collUserEquipements = null;
		$this->singleUserInformation = null;
		$this->singleUserProfile = null;
		$this->collUserRidess = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUsers:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUsers::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUsers
