<?php

/**
 * Base class that represents a row from the 'user_rides' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/28/09 19:43:55
 *
 * @package    lib.model.om
 */
abstract class BaseUserRides extends BaseObject  implements Persistent {


  const PEER = 'UserRidesPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserRidesPeer
	 */
	protected static $peer;

	/**
	 * The value for the user_ride_id field.
	 * @var        int
	 */
	protected $user_ride_id;

	/**
	 * The value for the ride_id field.
	 * @var        int
	 */
	protected $ride_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the mileage field.
	 * Note: this column has a database default value of: '0.00'
	 * @var        string
	 */
	protected $mileage;

	/**
	 * The value for the altitude_gain field.
	 * Note: this column has a database default value of: '0.00'
	 * @var        string
	 */
	protected $altitude_gain;

	/**
	 * @var        Rides
	 */
	protected $aRides;

	/**
	 * @var        Users
	 */
	protected $aUsers;

	/**
	 * @var        array UserRideMap[] Collection to store aggregation of UserRideMap objects.
	 */
	protected $collUserRideMaps;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserRideMaps.
	 */
	private $lastUserRideMapCriteria = null;

	/**
	 * @var        array UserStats[] Collection to store aggregation of UserStats objects.
	 */
	protected $collUserStatss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserStatss.
	 */
	private $lastUserStatsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUserRides object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->mileage = '0.00';
		$this->altitude_gain = '0.00';
	}

	/**
	 * Get the [user_ride_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserRideId()
	{
		return $this->user_ride_id;
	}

	/**
	 * Get the [ride_id] column value.
	 * 
	 * @return     int
	 */
	public function getRideId()
	{
		return $this->ride_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [mileage] column value.
	 * 
	 * @return     string
	 */
	public function getMileage()
	{
		return $this->mileage;
	}

	/**
	 * Get the [altitude_gain] column value.
	 * 
	 * @return     string
	 */
	public function getAltitudeGain()
	{
		return $this->altitude_gain;
	}

	/**
	 * Set the value of [user_ride_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserRides The current object (for fluent API support)
	 */
	public function setUserRideId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_ride_id !== $v) {
			$this->user_ride_id = $v;
			$this->modifiedColumns[] = UserRidesPeer::USER_RIDE_ID;
		}

		return $this;
	} // setUserRideId()

	/**
	 * Set the value of [ride_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserRides The current object (for fluent API support)
	 */
	public function setRideId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ride_id !== $v) {
			$this->ride_id = $v;
			$this->modifiedColumns[] = UserRidesPeer::RIDE_ID;
		}

		if ($this->aRides !== null && $this->aRides->getRideKey() !== $v) {
			$this->aRides = null;
		}

		return $this;
	} // setRideId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     UserRides The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = UserRidesPeer::USER_ID;
		}

		if ($this->aUsers !== null && $this->aUsers->getUserId() !== $v) {
			$this->aUsers = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     UserRides The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = UserRidesPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [mileage] column.
	 * 
	 * @param      string $v new value
	 * @return     UserRides The current object (for fluent API support)
	 */
	public function setMileage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mileage !== $v || $v === '0.00') {
			$this->mileage = $v;
			$this->modifiedColumns[] = UserRidesPeer::MILEAGE;
		}

		return $this;
	} // setMileage()

	/**
	 * Set the value of [altitude_gain] column.
	 * 
	 * @param      string $v new value
	 * @return     UserRides The current object (for fluent API support)
	 */
	public function setAltitudeGain($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->altitude_gain !== $v || $v === '0.00') {
			$this->altitude_gain = $v;
			$this->modifiedColumns[] = UserRidesPeer::ALTITUDE_GAIN;
		}

		return $this;
	} // setAltitudeGain()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(UserRidesPeer::MILEAGE,UserRidesPeer::ALTITUDE_GAIN))) {
				return false;
			}

			if ($this->mileage !== '0.00') {
				return false;
			}

			if ($this->altitude_gain !== '0.00') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->user_ride_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->ride_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->user_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->description = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->mileage = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->altitude_gain = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = UserRidesPeer::NUM_COLUMNS - UserRidesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating UserRides object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aRides !== null && $this->ride_id !== $this->aRides->getRideKey()) {
			$this->aRides = null;
		}
		if ($this->aUsers !== null && $this->user_id !== $this->aUsers->getUserId()) {
			$this->aUsers = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserRidesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserRidesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aRides = null;
			$this->aUsers = null;
			$this->collUserRideMaps = null;
			$this->lastUserRideMapCriteria = null;

			$this->collUserStatss = null;
			$this->lastUserStatsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserRides:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserRidesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UserRidesPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUserRides:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUserRides:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserRidesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUserRides:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UserRidesPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRides !== null) {
				if ($this->aRides->isModified() || $this->aRides->isNew()) {
					$affectedRows += $this->aRides->save($con);
				}
				$this->setRides($this->aRides);
			}

			if ($this->aUsers !== null) {
				if ($this->aUsers->isModified() || $this->aUsers->isNew()) {
					$affectedRows += $this->aUsers->save($con);
				}
				$this->setUsers($this->aUsers);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserRidesPeer::USER_RIDE_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserRidesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setUserRideId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserRidesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collUserRideMaps !== null) {
				foreach ($this->collUserRideMaps as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserStatss !== null) {
				foreach ($this->collUserStatss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRides !== null) {
				if (!$this->aRides->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRides->getValidationFailures());
				}
			}

			if ($this->aUsers !== null) {
				if (!$this->aUsers->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsers->getValidationFailures());
				}
			}


			if (($retval = UserRidesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collUserRideMaps !== null) {
					foreach ($this->collUserRideMaps as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserStatss !== null) {
					foreach ($this->collUserStatss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserRidesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getUserRideId();
				break;
			case 1:
				return $this->getRideId();
				break;
			case 2:
				return $this->getUserId();
				break;
			case 3:
				return $this->getDescription();
				break;
			case 4:
				return $this->getMileage();
				break;
			case 5:
				return $this->getAltitudeGain();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserRidesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getUserRideId(),
			$keys[1] => $this->getRideId(),
			$keys[2] => $this->getUserId(),
			$keys[3] => $this->getDescription(),
			$keys[4] => $this->getMileage(),
			$keys[5] => $this->getAltitudeGain(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserRidesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setUserRideId($value);
				break;
			case 1:
				$this->setRideId($value);
				break;
			case 2:
				$this->setUserId($value);
				break;
			case 3:
				$this->setDescription($value);
				break;
			case 4:
				$this->setMileage($value);
				break;
			case 5:
				$this->setAltitudeGain($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserRidesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setUserRideId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRideId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUserId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDescription($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setMileage($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setAltitudeGain($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserRidesPeer::USER_RIDE_ID)) $criteria->add(UserRidesPeer::USER_RIDE_ID, $this->user_ride_id);
		if ($this->isColumnModified(UserRidesPeer::RIDE_ID)) $criteria->add(UserRidesPeer::RIDE_ID, $this->ride_id);
		if ($this->isColumnModified(UserRidesPeer::USER_ID)) $criteria->add(UserRidesPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(UserRidesPeer::DESCRIPTION)) $criteria->add(UserRidesPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(UserRidesPeer::MILEAGE)) $criteria->add(UserRidesPeer::MILEAGE, $this->mileage);
		if ($this->isColumnModified(UserRidesPeer::ALTITUDE_GAIN)) $criteria->add(UserRidesPeer::ALTITUDE_GAIN, $this->altitude_gain);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);

		$criteria->add(UserRidesPeer::USER_RIDE_ID, $this->user_ride_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getUserRideId();
	}

	/**
	 * Generic method to set the primary key (user_ride_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setUserRideId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of UserRides (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setRideId($this->ride_id);

		$copyObj->setUserId($this->user_id);

		$copyObj->setDescription($this->description);

		$copyObj->setMileage($this->mileage);

		$copyObj->setAltitudeGain($this->altitude_gain);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getUserRideMaps() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserRideMap($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserStatss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserStats($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setUserRideId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     UserRides Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserRidesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserRidesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Rides object.
	 *
	 * @param      Rides $v
	 * @return     UserRides The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRides(Rides $v = null)
	{
		if ($v === null) {
			$this->setRideId(NULL);
		} else {
			$this->setRideId($v->getRideKey());
		}

		$this->aRides = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Rides object, it will not be re-added.
		if ($v !== null) {
			$v->addUserRides($this);
		}

		return $this;
	}


	/**
	 * Get the associated Rides object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Rides The associated Rides object.
	 * @throws     PropelException
	 */
	public function getRides(PropelPDO $con = null)
	{
		if ($this->aRides === null && ($this->ride_id !== null)) {
			$c = new Criteria(RidesPeer::DATABASE_NAME);
			$c->add(RidesPeer::RIDE_KEY, $this->ride_id);
			$this->aRides = RidesPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRides->addUserRidess($this);
			 */
		}
		return $this->aRides;
	}

	/**
	 * Declares an association between this object and a Users object.
	 *
	 * @param      Users $v
	 * @return     UserRides The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsers(Users $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getUserId());
		}

		$this->aUsers = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Users object, it will not be re-added.
		if ($v !== null) {
			$v->addUserRides($this);
		}

		return $this;
	}


	/**
	 * Get the associated Users object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Users The associated Users object.
	 * @throws     PropelException
	 */
	public function getUsers(PropelPDO $con = null)
	{
		if ($this->aUsers === null && ($this->user_id !== null)) {
			$c = new Criteria(UsersPeer::DATABASE_NAME);
			$c->add(UsersPeer::USER_ID, $this->user_id);
			$this->aUsers = UsersPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsers->addUserRidess($this);
			 */
		}
		return $this->aUsers;
	}

	/**
	 * Clears out the collUserRideMaps collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserRideMaps()
	 */
	public function clearUserRideMaps()
	{
		$this->collUserRideMaps = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserRideMaps collection (array).
	 *
	 * By default this just sets the collUserRideMaps collection to an empty array (like clearcollUserRideMaps());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserRideMaps()
	{
		$this->collUserRideMaps = array();
	}

	/**
	 * Gets an array of UserRideMap objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this UserRides has previously been saved, it will retrieve
	 * related UserRideMaps from storage. If this UserRides is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserRideMap[]
	 * @throws     PropelException
	 */
	public function getUserRideMaps($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserRideMaps === null) {
			if ($this->isNew()) {
			   $this->collUserRideMaps = array();
			} else {

				$criteria->add(UserRideMapPeer::USER_RIDE_ID, $this->user_ride_id);

				UserRideMapPeer::addSelectColumns($criteria);
				$this->collUserRideMaps = UserRideMapPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserRideMapPeer::USER_RIDE_ID, $this->user_ride_id);

				UserRideMapPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserRideMapCriteria) || !$this->lastUserRideMapCriteria->equals($criteria)) {
					$this->collUserRideMaps = UserRideMapPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserRideMapCriteria = $criteria;
		return $this->collUserRideMaps;
	}

	/**
	 * Returns the number of related UserRideMap objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserRideMap objects.
	 * @throws     PropelException
	 */
	public function countUserRideMaps(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserRideMaps === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserRideMapPeer::USER_RIDE_ID, $this->user_ride_id);

				$count = UserRideMapPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserRideMapPeer::USER_RIDE_ID, $this->user_ride_id);

				if (!isset($this->lastUserRideMapCriteria) || !$this->lastUserRideMapCriteria->equals($criteria)) {
					$count = UserRideMapPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserRideMaps);
				}
			} else {
				$count = count($this->collUserRideMaps);
			}
		}
		$this->lastUserRideMapCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserRideMap object to this object
	 * through the UserRideMap foreign key attribute.
	 *
	 * @param      UserRideMap $l UserRideMap
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserRideMap(UserRideMap $l)
	{
		if ($this->collUserRideMaps === null) {
			$this->initUserRideMaps();
		}
		if (!in_array($l, $this->collUserRideMaps, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserRideMaps, $l);
			$l->setUserRides($this);
		}
	}

	/**
	 * Clears out the collUserStatss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserStatss()
	 */
	public function clearUserStatss()
	{
		$this->collUserStatss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserStatss collection (array).
	 *
	 * By default this just sets the collUserStatss collection to an empty array (like clearcollUserStatss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserStatss()
	{
		$this->collUserStatss = array();
	}

	/**
	 * Gets an array of UserStats objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this UserRides has previously been saved, it will retrieve
	 * related UserStatss from storage. If this UserRides is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserStats[]
	 * @throws     PropelException
	 */
	public function getUserStatss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserStatss === null) {
			if ($this->isNew()) {
			   $this->collUserStatss = array();
			} else {

				$criteria->add(UserStatsPeer::RIDE_KEY, $this->user_ride_id);

				UserStatsPeer::addSelectColumns($criteria);
				$this->collUserStatss = UserStatsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserStatsPeer::RIDE_KEY, $this->user_ride_id);

				UserStatsPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserStatsCriteria) || !$this->lastUserStatsCriteria->equals($criteria)) {
					$this->collUserStatss = UserStatsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserStatsCriteria = $criteria;
		return $this->collUserStatss;
	}

	/**
	 * Returns the number of related UserStats objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserStats objects.
	 * @throws     PropelException
	 */
	public function countUserStatss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserStatss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserStatsPeer::RIDE_KEY, $this->user_ride_id);

				$count = UserStatsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserStatsPeer::RIDE_KEY, $this->user_ride_id);

				if (!isset($this->lastUserStatsCriteria) || !$this->lastUserStatsCriteria->equals($criteria)) {
					$count = UserStatsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserStatss);
				}
			} else {
				$count = count($this->collUserStatss);
			}
		}
		$this->lastUserStatsCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a UserStats object to this object
	 * through the UserStats foreign key attribute.
	 *
	 * @param      UserStats $l UserStats
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserStats(UserStats $l)
	{
		if ($this->collUserStatss === null) {
			$this->initUserStatss();
		}
		if (!in_array($l, $this->collUserStatss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserStatss, $l);
			$l->setUserRides($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this UserRides is new, it will return
	 * an empty collection; or if this UserRides has previously
	 * been saved, it will retrieve related UserStatss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in UserRides.
	 */
	public function getUserStatssJoinUserBikes($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserRidesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserStatss === null) {
			if ($this->isNew()) {
				$this->collUserStatss = array();
			} else {

				$criteria->add(UserStatsPeer::RIDE_KEY, $this->user_ride_id);

				$this->collUserStatss = UserStatsPeer::doSelectJoinUserBikes($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserStatsPeer::RIDE_KEY, $this->user_ride_id);

			if (!isset($this->lastUserStatsCriteria) || !$this->lastUserStatsCriteria->equals($criteria)) {
				$this->collUserStatss = UserStatsPeer::doSelectJoinUserBikes($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserStatsCriteria = $criteria;

		return $this->collUserStatss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collUserRideMaps) {
				foreach ((array) $this->collUserRideMaps as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserStatss) {
				foreach ((array) $this->collUserStatss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collUserRideMaps = null;
		$this->collUserStatss = null;
			$this->aRides = null;
			$this->aUsers = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUserRides:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUserRides::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUserRides
