<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/06/28 10:39:29
sfConfig::add(array(
  'app_params_to_escape_list' => array (
  0 => 'loadingString',
  1 => 'closeString',
),
));
