<?php
// auto-generated by sfPropelCrud
// date: 2008/12/07 21:34:35
?>
<h1>userbike</h1>

<table>
<thead>
<tr>
  <th>User</th>
  <th>User bike</th>
  <th>Bike year</th>
  <th>Bike make</th>
  <th>Bike model</th>
  <th>Equip function</th>
</tr>
</thead>
<tbody>
<?php foreach ($user_bikess as $user_bikes): ?>
<tr>
    <td><?php echo $user_bikes->getUserId() ?></td>
      <td><?php echo link_to($user_bikes->getUserBikeId(), 'userbike/show?user_bike_id='.$user_bikes->getUserBikeId()) ?></td>
      <td><?php echo $user_bikes->getBikeYear() ?></td>
      <td><?php echo $user_bikes->getBikeMake() ?></td>
      <td><?php echo $user_bikes->getBikeModel() ?></td>
      <td><?php echo $user_bikes->getEquipFunction() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'userbike/create') ?>
