dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'mysql:host=localhost;dbname=cycleBrainDev'
      username: cyclebrain
      password: cyclebrain
      encoding: utf8
      persistent: true
      pooling: true
