<?php
// auto-generated by sfPropelCrud
// date: 2008/12/07 21:35:02
?>
<table>
<tbody>
<tr>
<th>User ride: </th>
<td><?php echo $user_rides->getUserRideId() ?></td>
</tr>
<tr>
<th>Ride: </th>
<td><?php echo $user_rides->getRideId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $user_rides->getUserId() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $user_rides->getDescription() ?></td>
</tr>
<tr>
<th>Mileage: </th>
<td><?php echo $user_rides->getMileage() ?></td>
</tr>
<tr>
<th>Altitude gain: </th>
<td><?php echo $user_rides->getAltitudeGain() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'userrides/edit?user_ride_id='.$user_rides->getUserRideId()) ?>
&nbsp;<?php echo link_to('list', 'userrides/list') ?>
