<?php
// auto-generated by sfPropelCrud
// date: 2008/12/07 14:48:57
?>
<h1>users</h1>

<table>
<thead>
<tr>
  <th>Username</th>
  <th>Password</th>
  <th>Fname</th>
  <th>Lname</th>
  <th>Email</th>
  <th>User</th>
</tr>
</thead>
<tbody>
<?php foreach ($userss as $users): ?>
<tr>
    <td><?php echo $users->getUsername() ?></td>
      <td><?php echo $users->getPassword() ?></td>
      <td><?php echo $users->getFname() ?></td>
      <td><?php echo $users->getLname() ?></td>
      <td><?php echo $users->getEmail() ?></td>
      <td><?php echo link_to($users->getUserId(), 'users/show?user_id='.$users->getUserId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'users/create') ?>
