<?php
// auto-generated by sfPropelCrud
// date: 2008/12/07 14:48:57
?>
<table>
<tbody>
<tr>
<th>Username: </th>
<td><?php echo $users->getUsername() ?></td>
</tr>
<tr>
<th>Password: </th>
<td><?php echo $users->getPassword() ?></td>
</tr>
<tr>
<th>Fname: </th>
<td><?php echo $users->getFname() ?></td>
</tr>
<tr>
<th>Lname: </th>
<td><?php echo $users->getLname() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $users->getEmail() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $users->getUserId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'users/edit?user_id='.$users->getUserId()) ?>
&nbsp;<?php echo link_to('list', 'users/list') ?>
