<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/04/26 08:27:12
sfConfig::add(array(
  'app_params_to_escape_list' => array (
  0 => 'loadingString',
  1 => 'closeString',
),
));
