<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/06/15 18:57:42
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
