<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/05/29 21:49:37
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'add' => 
  array (
    'is_secure' => false,
  ),
  'authenticate' => 
  array (
    'is_secure' => false,
  ),
  'newuser' => 
  array (
    'is_secure' => false,
  ),
  'forgot' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
