<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/05/03 20:31:36

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=cycleBrainDev',
  'username' => 'cyclebrain',
  'password' => 'cyclebrain',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
