<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/05/03 20:31:34
sfConfig::add(array(
  'app_params_to_escape_list' => array (
  0 => 'loadingString',
  1 => 'closeString',
),
));
